[General]
AllowGrabBaseKeypad=true
AllowGrabBaseSpecial=false
AllowGrabLocks=false
AllowGrabMiscKeypad=true
AllowGrabMiscSpecial=true
MultipleActionsBehaviour=first
WindowSize=@Size(750 400)

[Alt%2BF1.1]
Comment=显示/隐藏主菜单
Enabled=true
path=/panel/mainmenu/show_hide

[Alt%2BF1.2]
Comment=显示/隐藏主菜单
Enabled=true
path=/panel/fancymenu2/show_hide

[Alt%2BF2.3]
Comment=显示/隐藏对话框
Enabled=true
path=/runner/show_hide_dialog

[Control%2BAlt%2BD.4]
Comment=显示桌面
Enabled=true
path=/panel/showdesktop/show_hide

[Control%2BAlt%2BT.34]
Comment=打开终端
Enabled=true
Exec=/usr/bin/qterminal

[Control%2BF1.5]
Comment=切换至桌面 1
Enabled=true
path=/panel/desktopswitch/desktop_1

[Control%2BF10.6]
Comment=切换至桌面 10
Enabled=true
path=/panel/desktopswitch/desktop_10

[Control%2BF11.7]
Comment=切换至桌面 11
Enabled=true
path=/panel/desktopswitch/desktop_11

[Control%2BF12.8]
Comment=切换至桌面 12
Enabled=true
path=/panel/desktopswitch/desktop_12

[Control%2BF2.9]
Comment=切换至桌面 2
Enabled=true
path=/panel/desktopswitch/desktop_2

[Control%2BF3.10]
Comment=切换至桌面 3
Enabled=true
path=/panel/desktopswitch/desktop_3

[Control%2BF4.11]
Comment=切换至桌面 4
Enabled=true
path=/panel/desktopswitch/desktop_4

[Control%2BF5.12]
Comment=切换至桌面 5
Enabled=true
path=/panel/desktopswitch/desktop_5

[Control%2BF6.13]
Comment=切换至桌面 6
Enabled=true
path=/panel/desktopswitch/desktop_6

[Control%2BF7.14]
Comment=切换至桌面 7
Enabled=true
path=/panel/desktopswitch/desktop_7

[Control%2BF8.15]
Comment=切换至桌面 8
Enabled=true
path=/panel/desktopswitch/desktop_8

[Control%2BF9.16]
Comment=切换至桌面 9
Enabled=true
path=/panel/desktopswitch/desktop_9

[Meta%2B0.17]
Comment=激活任务 10
Enabled=true
path=/panel/taskbar/task_10

[Meta%2B1.18]
Comment=激活任务 1
Enabled=true
path=/panel/taskbar/task_1

[Meta%2B2.19]
Comment=激活任务 2
Enabled=true
path=/panel/taskbar/task_2

[Meta%2B3.20]
Comment=激活任务 3
Enabled=true
path=/panel/taskbar/task_3

[Meta%2B4.21]
Comment=激活任务 4
Enabled=true
path=/panel/taskbar/task_4

[Meta%2B5.22]
Comment=激活任务 5
Enabled=true
path=/panel/taskbar/task_5

[Meta%2B6.23]
Comment=激活任务 6
Enabled=true
path=/panel/taskbar/task_6

[Meta%2B7.24]
Comment=激活任务 7
Enabled=true
path=/panel/taskbar/task_7

[Meta%2B8.25]
Comment=激活任务 8
Enabled=true
path=/panel/taskbar/task_8

[Meta%2B9.26]
Comment=激活任务 9
Enabled=true
path=/panel/taskbar/task_9

[XF86AudioLowerVolume.27]
Comment=减小音量
Enabled=true
path=/panel/volume/down

[XF86AudioMute.28]
Comment=静音/取消静音
Enabled=true
path=/panel/volume/mute

[XF86AudioRaiseVolume.29]
Comment=增大音量
Enabled=true
path=/panel/volume/up

[XF86Eject.30]
Comment=弹出可移动媒体
Enabled=true
path=/panel/mount/eject

[XF86PowerOff.31]
Comment=关闭电源按键操作
Enabled=true
path=/powermanager/keypoweroff

[XF86Sleep.32]
Comment=休眠的按键操作
Enabled=true
path=/powermanager/keyhibernate

[XF86Suspend.33]
Comment=暂停的按键操作
Enabled=true
path=/powermanager/keysuspend
