[General]
__userfile__=true
window_manager=xfwm4

[Environment]
BROWSER=firefox
GTK_CSD=0
GTK_OVERLAY_SCROLLING=0
TERM=qterminal

[Mouse]
cursor_size=16
cursor_theme=bloom

[Touchpad]
SynPS%252F2%2520Synaptics%2520TouchPad\accelSpeed=-2.7755575615628914e-17
SynPS%252F2%2520Synaptics%2520TouchPad\naturalScrollingEnabled=1
SynPS%252F2%2520Synaptics%2520TouchPad\scrollingMethodEnabled=1
SynPS%252F2%2520Synaptics%2520TouchPad\tapToDragEnabled=1
SynPS%252F2%2520Synaptics%2520TouchPad\tappingEnabled=1
